//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResinTimer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ResinTimer.Properties.UserSettings defaultInstance = ((ResinTimer.Properties.UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ResinTimer.Properties.UserSettings())));
        
        public static ResinTimer.Properties.UserSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
