name: Build

on:
  push:
    branches: [ master, win11 ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


env:
  DOTNET_VERSION: 7.0.x
  BUILD_TARGET: .\src\SilentSelene.sln


jobs:
  build:
    name: .NET Build
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
      
    - name: Build
      run: dotnet build ${{ env.BUILD_TARGET }} -c Release
